templates/tsconfig.json, tsconfig.base.json
Since we are teaching `app/` dir architecture from winter 2023, some changes are needed to the ESLint config for Next.js
Moving the `include` array into the template was necessary because Next.js tries to modify `tsconfig.json`, causing this error:
```
TypeError: Cannot read properties of undefined (reading 'push')
at Object.writeConfigurationDefaults (/Users/josehower/projects/next-13-demo-project/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:207:30)
at async Object.verifyTypeScriptSetup (/Users/josehower/projects/next-13-demo-project/node_modules/next/dist/lib/verifyTypeScriptSetup.js:116:9)
at async DevServer.verifyTypeScript (/Users/josehower/projects/next-13-demo-project/node_modules/next/dist/server/dev/next-dev-server.js:486:34)
at async DevServer.prepare …
```
=> Add configuration for Next.js 13 app/ dir (#183)ude 

__tests__/stylelint.config.cjs, package.json, stylelint.config.cjs, templates/stylelint.config.cjs, yarn.lock
Since we're teaching CSS Modules with Sass (scss) for the `app` directory in Next.js 13+, enable Stylelint linting for those files.
=> Enable Stylelint linting for CSS Modules + scss

bin/install.js, readme.md
=> Remove Yarn support, rely on auto-install-peers (#213

index.cjs
With the current configuration out of the box, our eslint is ignoring .cjs, .mjs, .cts, .mts and .jsx files:
this can be tested in the following reproduction repo:
https://stackblitz.com/edit/github-7bne77?file=README.md
steps to reproduce:
1. run `pnpm eslint . --max-warnings 0 `
2. check ESLint is not running in ./index.cjs
3. run `pnpm eslint "**/*.cjs" --max-warnings 0`
4. check now the file is checked as expected
based on the [official documentation](https://eslint.org/docs/latest/use/configure/configuration-files#specifying-target-files-to-lint:~:text=If%20you%20specified,of%20overrides%20entries.):
> ESLint searches target files in the directory to lint. The target files are *.js or the files that match any of overrides entries 
so by default, .only .js files are going to be linted …
=> Add override to support additional file extensions

__tests__/package.json, __tests__/pnpm-lock.yaml, __tests__/stylelint.config.cjs, bin/install.js, package.json, pnpm-lock.yaml, templates/stylelint.config.cjs
close https://github.com/upleveled/eslint-config-upleveled/issues/218
since now we have the [Stylelint config as a standalone package](https://www.npmjs.com/package/stylelint-config-upleveled) we want to use the package instead of the manual installation we have been doing.
This PR updates the script to install the standalone package and simplifies the configuration template for Stylelint
=> Use stylelint-config-upleveled standalone package

index.cjs
This PR adds a capturing group to the regular expression used in ESLint. Previously, the regular expression, for example, `/^div|h1|h2|h3|h4|h5|h6|hr|ol|p|table|ul$/`, caused an issue due to the missing of the capturing group when using the pipe character, resulting in individual character matching instead of the entire string. This update adds a capturing group to match any of the allowed element names.
=> Fix regex with capturing group

bin/install.js
This PR adds TypeScript to the devDependencies that ESLint is installing. The purpose of this change is to fix an error that occurs when running any linting processes (including `pnpm start` in a `create-react-app`), which indicates that TypeScript is missing from the `node_modules`.
```
Error: Cannot find module 'typescript' from 
'/Users/lukas/Documents/projects/pnpm-react-color-generator/node_modules'
```
Other tooling may also expect `typescript` to be installed in `node_modules/typescript` and the bins to be available in `node_modules/.bin`
With this change, the TypeScript package will be installed automatically when running the ESLint installation.
To test the changes, I edited the code in the `eslint-config-upleveled install.js` file inside `node_modules`. Then, I ran `pnpm …
=> Add TS to devDependencies in ESLint installation

bin/install.js
This PR adds a `packageManager` option to the `package.json` file for projects that use `@upleveled/react-scripts` and do not already have a `packageManager` specified. This option is set to the latest version of pnpm, fetched from the npm registry API. Netlify currently uses `pnpm v7`, which can cause issues with deer dependencies. Adding this option will ensure that the correct version of pnpm is used for deployment.
This is the error message when deploying on Netlify without specifying the `packageManager`: 
```
10:07:47 AM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit 
10:07:47 AM: hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
10:07:47 …
```
=> Configure pnpm v8+ for Netlify

index.cjs
Setting an override for the `json` type in SafeQL, so that we can safely use the `json_agg` aggregate function to return `json` array from SQL queries without throwing a SafeQL error according to this issue comment in SafeQL
https://github.com/ts-safeql/safeql/issues/102#issuecomment-1318322571
=> Add type override for json_agg

bin/install.js, package.json, pnpm-lock.yaml, templates/next-js-postgresql/prettier.config.mjs
Our Prettier configuration has formatted almost all of the files that we use in our courses:
- ✅ JavaScript and TypeScript w. JSX
- ✅ CSS
- ✅ CSS in template literals
- ✅ GraphQL
- ✅ GraphQL in template literals
- ❌ SQL in template literals
Formatting SQL in template literals has not been easy to achieve, [I've been waiting years for this](https://twitter.com/karlhorky/status/1717581981620281508).
Challenges:
1. Although solutions like [`eslint-plugin-sql` with `eslint-plugin-unicorn`](https://github.com/gajus/eslint-plugin-sql/pull/33#issuecomment-1666585459) exist in the ESLint ecosystem (lint problems on non-formatted strings, with auto-fix) we don't really want to require students to enable auto-fix in ESLint, because it's slow
2. Prettier plugins like …
=> Add Prettier plugins to format SQL in JS / TS

index.js, package.json, pnpm-lock.yaml
Switch to `.gitignore`-based ignores, by using https://github.com/antfu/eslint-config-flat-gitignore
Our existing ignores config below has entries which are already in `.gitignore`:
```js
ignores: [
// Next.js cache
'.next/**/*',
// Next.js builds
//
// Also `@upleveled/create-react-app` builds, until we migrate
// everything to Next.js
// https://github.com/upleveled/create-react-app/pull/2
// TODO: Remove this part of the comment once we migrate
// everything from create-react-app to Next.js
'build/**/*',
],
```
It also doesn't seem to make much sense to lint files which are in `.gitignore`. Will revisit in future if necessary.
=> Switch ESLint `ignores` config to .gitignore

tsconfig.base.json
> `moduleDetection`
>
> This setting controls how TypeScript determines whether a file is a script or a module
>
> "force" - Ensures that every non-declaration file is treated as a module.
https://www.typescriptlang.org/tsconfig#:~:text=Ensures%20that%20every%20non%2Ddeclaration%20file%20is%20treated%20as%20a%20module.
=> Set "moduleDetection": "force" in tsconfig.json

templates/node-js/tsconfig.json, tsconfig.base.json
Switch `"module"` config in `tsconfig.json`:
1. Switch `"module": "ESNext"` to `"module": "Preserve"` for bundler environments
2. Switch `"module": "ESNext"` to `"module": "NodeNext"` for Node.js
3. Switch `"moduleResolution": "Bundler"` to `"moduleResolution": "NodeNext"` for Node.js
1. According to Matt Pocock, `"module": "Preserve"` more closely matches what bundlers do than `"module": "ESNext"`:
- https://twitter.com/mattpocockuk/status/1766064573130444872
- https://www.totaltypescript.com/tsconfig-cheat-sheet#not-transpiling-with-typescript
2. Also according to Matt Pocock, `"module": "NodeNext"` and `"moduleResolution": "NodeNext"` should be used if transpiling with `tsc` (which would be the case for Node.js projects)
=> Switch module config in tsconfig.json

index.js
Now that [`dotenv-safe` is maintained again](https://github.com/rolodato/dotenv-safe/issues/128#issuecomment-1930553844), we can switch from `dotenv` back to `dotenv-safe`
=> Switch from dotenv back to dotenv-safe

templates/node-js/tsconfig.json, tsconfig.base.json
Remove unnecessary `moduleResolution` config, since it is automatically set to the value we want:
> It's a great day. You can forget `moduleResolution` exists, and delete it from your tsconfig.json.
>
> It's now implied by the only two valid 'module' options:
>
> "module": "preserve" -> "moduleResolution": "bundler"
> "module": "nodenext" -> "moduleResolution": "nodenext"
Source:
- https://twitter.com/mattpocockuk/status/1775138087443595689
- https://www.totaltypescript.com/tsconfig-cheat-sheet#:~:text=module%3A%20preserve%20is%20the%20best%20option%20because%20it%20most%20closely%20mimics%20how%20bundlers%20treat%20modules.%20moduleResolution%3A%20Bundler%20is%20implied%20from%20this%20option.
=> Remove moduleResolution from tsconfig.json

package.json
Corepack adds a new `"packageManager"` property to `package.json` since [`corepack@0.26.0`](https://github.com/nodejs/corepack/releases/tag/v0.26.0) (PR: https://github.com/nodejs/corepack/pull/413)
```bash
$ pnpm install
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@9.1.1+sha256.9551e803dcb7a1839fdf5416153a844060c7bce013218ce823410532504ac10b.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
```
=> Add `packageManager` to `package.json`

package.json, pnpm-lock.yaml
Upgrade `@typescript-eslint` packages to v7 alpha to avoid [the "Too many files (>8) have matched the default project" error](https://github.com/typescript-eslint/typescript-eslint/issues/9032)
=> Upgrade @typescript-eslint packages to v7 alpha

bin/install.js, templates/expo-postgresql/eslint.config.js, templates/expo-postgresql/prettier.config.js, templates/expo-postgresql/tsconfig.json
This PR adds a new project type to UpLeveled ESLint. Previously, if a project had `postgres` installed, ESLint assumed it was a Next.js application. Now, with the use of Expo Router, we can set up PostgreSQL in an Expo React Native project. This update ensures that ESLint correctly identifies Expo projects with PostgreSQL.
=> Add support for Expo with PostgreSQL

index.js
No longer needed - Bun modules are supported in latest `eslint-import-resolver-typescript@3.6.3` version:
- https://github.com/un-ts/eslint-plugin-import-x/issues/92#issuecomment-2312113726
=> Remove no-unresolved ignore for bun modules

index.js
> The old "import assertions" proposal has been renamed to "import attributes" with the following major changes:
>
> 1. The keyword is now `with` instead of `assert`.
> 2. Unknown assertions cause an error rather than being ignored.
- https://github.com/tc39/proposal-import-attributes/issues/6#issuecomment-1492361854
- https://github.com/v8/v8/commit/159c82c5e6392e78b9bba7161b1bed6e23758984
- https://github.com/nodejs/node/pull/50140
- https://nodejs.org/en/blog/release/v20.10.0/
=> Switch import assertions (`assert`) to import attributes (`with`)

index.js
Prevent `Unsafe member access .attending on an `any` value.` problems being reported in `.jsx` files which are not reported with other JavaScript file extensions.
```js
const response = await fetch('http://localhost:3000/guests/1');
const updatedGuest = await response.json();
console.log(updatedGuest.attending);
```
=> Update index.js with '**/*.jsx'

tsconfig.base.json
Closes #394
TypeScript 5.5 introduced `${configDir}`, for specifying the directory where the config is:
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#the-configdir-template-variable-for-configuration-files
- https://github.com/microsoft/TypeScript/issues/37227
- https://github.com/microsoft/TypeScript/issues/51213
- https://github.com/microsoft/TypeScript/issues/57485
- https://github.com/microsoft/TypeScript/pull/58042
We can use this to avoid the brittle relative paths in the `tsconfig.base.json` file
=> Switch relative path to TS 5.5 ${configDir}

tsconfig.base.json
Closes #430
Simplify the `tsconfig.base.json` file, heavily inspired by [the Total TypeScript TSConfig Cheat Sheet](https://www.totaltypescript.com/tsconfig-cheat-sheet)
- `isolatedModules`: already `true` with `verbatimModuleSyntax` https://www.typescriptlang.org/tsconfig/#isolatedModules
- `forceConsistentCasingInFileNames`: `true` by default https://www.typescriptlang.org/tsconfig/#forceConsistentCasingInFileNames
TODO:
=> Simplify and modernize `tsconfig.base.json`

index.js
Closes #395
Add enforcement for Expo API Routes function return types using [the `ExpoApiResponse` type](https://github.com/upleveled/expo-example-spring-2024-atvie/pull/4/commits/98e83ec403f84e28ab454018bc92052f78a33fe5), first proposed in https://github.com/expo/expo/issues/30521
=> Enforce Expo API Route response type checking

bin/expo-setup.js
Configure [Expo Router Typed Routes](https://docs.expo.dev/router/reference/typed-routes) during Expo setup
=> Configure Expo Router Typed Routes experiment

bin/expo-setup.js
[Expo allows usage `import` for importing images](https://docs.expo.dev/develop/user-interface/assets/#:~:text=You%20can%20import,statements.), but does not yet have types for paths which use common image formats.
Add a file `images.d.ts` which contains Type Declarations for common image formats, inspired by the `global.d.ts` file from Next.js.
=> Create images TS types for Expo `import` in images.d.ts

index.js
Warn about returning promises without `await`, which will result in worse stack traces
- https://typescript-eslint.io/rules/return-await/
=> Configure @typescript-eslint/return-await to warn on lacking await

bin/expo-setup.js, bin/install.js
Issue https://github.com/upleveled/courses/issues/3000
Follow up PR 
- https://github.com/upleveled/courses/pull/2925
Breaking change: the new config introduced in this PR is SDK 52 configuration for the New Architecture, so this should only be used with Expo SDK 52+
This PR updates the project configuration to align with changes introduced in Expo SDK 52. With SDK 52, the extra configuration steps required for SDK 51 are no longer needed. Running `pnpm create expo-app@latest .` now initializes the `app.json` file with:
- `expo.newArchEnabled = true`
- `expo.experiments.typedRoutes = true`
Additionally, we switch from `app.json` to `app.config.ts` to make [the config](https://docs.expo.dev/workflow/configuration/) more dynamic, add TS support, and make it easier to manage …
=> Breaking: Remove Expo SDK 51 config, switch to app.config.ts

bin/install.js
[pnpm v10 blocks lifecycle scripts by default](https://socket.dev/blog/pnpm-10-0-0-blocks-lifecycle-scripts-by-default), which can lead to hard-to-debug problems:
```bash
$ pnpm install
...
╭ Warning ───────────────────────────────────────────────────────────────────────────────────╮
│                                                                                            │
│   Ignored build scripts: bcrypt.                                                           │
│   Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.   │
│                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
$ pnpm build
...
Cannot find module …
```
=> Configure strict-dep-builds to fail on pnpm v10 ignored build scripts

index.js
Until this PR, expression sequences yielded warnings (line 1) unless they were wrapped in parentheses (line 2):
```ts
a(), b(); // ⚠️ Unexpected use of comma operator. eslint (no-sequences)
(a(), b()); // ✅
```
This pattern is however often an error, so this PR makes the expression sequences inside parentheses also yield warnings:
```ts
a(), b(); // ⚠️ Unexpected use of comma operator. eslint (no-sequences)
(a(), b()); // ⚠️ Unexpected use of comma operator. eslint (no-sequences)
```
=> Disallow expression sequences in parentheses

__tests__/package.json, readme.md
Allow `unrs-resolver` build scripts for pnpm, to avoid `Ignored build scripts: unrs-resolver` messages as shown below
```bash
➜  p mkdir a && cd a
➜  a pnpm init
Wrote to /Users/k/p/a/package.json
...
➜  a pnpm add --save-dev eslint-config-upleveled@latest
 WARN  1 deprecated subdependencies found: @babel/plugin-proposal-private-methods@7.18.6
Packages: +381
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 405, reused 345, downloaded 42, added 381, done
devDependencies:
+ eslint-config-upleveled 9.2.4
 ERR_PNPM_IGNORED_BUILDS  Ignored build scripts: unrs-resolver
Run "pnpm approve-builds" to pick which dependencies should be allowed to run …
```
=> Allow unrs-resolver build scripts for pnpm

.github/workflows/lint-check-types-test.yml
`actions/setup-node` has multiple days / weeks of lag behind new Node.js versions:
- https://github.com/actions/setup-node/issues/940
- https://github.com/actions/setup-node/issues/1236
Switch back to `actions/setup-node`, but with a hardcoded version number which is upgraded instead through Renovate bot PRs.
=> Switch to hardcoded Node.js version + Renovate to avoid action lag

index.js, package.json, pnpm-lock.yaml
Continuation of migration from #530
Follow the equivalent mapping in https://github.com/Rel1cx/eslint-react/issues/85 and the `eslint-plugin-react-x` rules in https://eslint-react.xyz/docs/rules/overview to migrate rest of `eslint-plugin-react` rules with equivalents to `eslint-plugin-react-x`, `eslint-plugin-react-dom`, `eslint-plugin-react-naming-convention`
Rules without an equivalent in `eslint-plugin-react-x`, `eslint-plugin-react-dom`, `eslint-plugin-react-naming-convention` will need to be migrated to ESLint Stylistic
=> Migrate rest of rules to eslint-plugin-react-x, -dom, -naming-convention

index.js, package.json, pnpm-lock.yaml
The `react-hooks/react-compiler` rule was split up into separate rules to offer clearer feedback to developers:
- https://github.com/facebook/react/pull/34117#issuecomment-3344189761
Migrate to all of the new rules listed as available in the RC section of [the `eslint-plugin-react-hooks` docs page](https://react.dev/reference/eslint-plugin-react-hooks), except for [`incompatible-library`](https://react.dev/reference/eslint-plugin-react-hooks/lints/incompatible-library), because this rule is not yet available:
- https://github.com/facebook/react/issues/34632
=> Migrate `react-hooks/react-compiler` to split up rules
